ekrixi-14/ekrixi

Content.Server/_FTL/AmbientHeater/AmbientHeaterComponent.cs
Content.Server/_FTL/AmbientHeater/AmbientHeaterSystem.cs
Resources/Prototypes/Entities/Structures/Power/Generation/generators.yml

Adds the ambientheater system which allows objects to randomly heat/cool down the environment

Generators and AmbientHeater system

---

Content.Shared/CCVar/CCVars.cs
Resources/Locale/en-US/info/rules.ftl

Ftl14 branding

---

Content.Server/_FTL/FTLPoints/DisposalFTLPointComponent.cs
Content.Server/_FTL/FTLPoints/FTLPointsSystem.cs
Content.Server/_FTL/FTLPoints/GeneratePointCommand.cs
Content.Server/_FTL/ShipHealth/FTLShipHealthSystem.cs
Resources/Prototypes/_FTL/Entities/Stations/independent.yml
Resources/Prototypes/_FTL/Maps/kestrel.yml

https://cdn.discordapp.com/attachments/1090860241106763816/1124644415512772658/2023-07-01_18-13-23.mp4
also removes centcom

FTL points

---

Resources/Locale/en-US/_ftl/ghost-roles.ftl
Resources/Maps/_FTL/trade-station.yml
Resources/Prototypes/Roles/Jobs/Cargo/cargo_technician.yml
Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
Resources/Prototypes/_FTL/Entities/Markers/Spawners/trader_station.yml
Resources/Prototypes/_FTL/Entities/Mobs/NPCs/trader_station.yml
Resources/Prototypes/_FTL/Maps/kestrel.yml

Job reorganization

---

Resources/Prototypes/_FTL/Entities/Objects/Weapons/Guns/Ammunition/explosive.yml
Resources/Prototypes/_FTL/Entities/Structures/Weapons/laser.yml
Resources/Prototypes/_FTL/Entities/Structures/Weapons/silo.yml

Missiles no longer explode when thrown

No more fragile missiles

---

Resources/Maps/_FTL/kestrel.yml

Replaces the plasma gen with a uranium gen

No more plasmagen

---

Content.Server/_FTL/FTLPoints/FTLPointsSystem.cs
Content.Server/_FTL/FTLPoints/GeneratePointCommand.cs

adds the ability to use prototypes instead of relying on rng

genpoint should be better now

---

Content.Client/_FTL/Weapons/WeaponMapControl.cs
Content.Client/_FTL/Weapons/WeaponTargetingWindow.xaml.cs
Content.Client/_FTL/Weapons/WeaponTargetingWindowBoundUserInterface.cs
Content.Server/_FTL/PowerControl/PowerControlSystem.cs
Content.Server/_FTL/SleeperCryopod/SleeperCryopodSystem.cs
Content.Server/_FTL/Weapons/WeaponTargetingComponent.cs
Content.Server/_FTL/Weapons/WeaponTargetingSystem.cs
Content.Shared/_FTL/Weapons/SharedWeaponTargetingSystem.cs
Resources/Locale/en-US/_ftl/weapons.ftl
Resources/ServerInfo/Guidebook/Security/GunsAndYou.xml

You cannot use the pad on link

---

Resources/Prototypes/Roles/Jobs/Cargo/cargo_technician.yml

OT is now cool

---

Content.Server/_FTL/Weapons/WeaponTargetingSystem.cs

fix transform crash

---

Content.Server/_FTL/FTLPoints/GeneratePointCommand.cs
Resources/Prototypes/_FTL/ftl_points.yml

change warp points up

---

Resources/Maps/_FTL/kestrel.yml

kestrel update yippee

---

.github/workflows/build-test-debug.yml
.github/workflows/build-test-release.yml
Content.Server/_FTL/FTLPoints/Effects/SpawnDungeonEffect.cs

Fix ruins breaking tests

---

Content.Server/NPC/Pathfinding/PathfindingSystem.Grid.cs
Content.Server/_FTL/FTLPoints/Effects/SpawnDungeonEffect.cs
Content.Server/_FTL/ShipTracker/ShipTrackerSystem.cs
Content.Shared/CCVar/CCVars.cs
Resources/Prototypes/_FTL/ftl_points.yml

Makes dungeon spawning more common

---

Resources/Locale/en-US/_ftl/crates.ftl
Resources/Prototypes/_FTL/Catalog/Cargo/cargo_security.yml
Resources/Prototypes/_FTL/Catalog/Fills/Crates/missiles.yml

Cargo can now order T1 and T2 weapons at a hefty price

You can now order a majority of T1 and T2 weapons

---

Content.Server/_FTL/FTLPoints/Effects/ApplyWorldGenConfigEffect.cs
Resources/Locale/en-US/_ftl/ships.ftl
Resources/Prototypes/_FTL/World/Biomes/packed.yml
Resources/Prototypes/_FTL/World/worldgen_packed.yml
Resources/Prototypes/_FTL/ftl_points.yml

Asteroid fields

---

Content.Client/Preferences/UI/HumanoidProfileEditor.xaml
Content.Client/Preferences/UI/HumanoidProfileEditor.xaml.cs
Content.Shared/Humanoid/Prototypes/SpeciesPrototype.cs
Content.Shared/Preferences/HumanoidCharacterProfile.cs
Resources/Prototypes/Species/dwarf.yml

Show height and balance height bounds

---

Content.Shared/CCVar/CCVars.cs
Resources/Locale/en-US/job/job-names.ftl
Resources/Prototypes/Roles/Jobs/Command/captain.yml
Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
Resources/Prototypes/_FTL/Roles/Jobs/Command/pilot.yml
Resources/Prototypes/_FTL/Roles/play_time_trackers.yml

Planning for a hubbed server playtest soon once I upgrade my server, AKA whenever I get the cash to do so, hahaha... Regarding playtests, for now, I'll still do some regular ones.

Command roles are now whitelisted

---

Content.Server/RoundEnd/RoundEndSystem.cs
Content.Server/_FTL/ShipRename/ShipRenameSystem.cs
Content.Shared/CCVar/CCVars.cs
Resources/Prototypes/_FTL/Entities/Structures/Machines/cryopod.yml
Resources/Prototypes/_FTL/Tiles/fluid.yml
Resources/Prototypes/_FTL/game_presets.yml
Resources/Prototypes/game_presets.yml
Resources/ServerInfo/Guidebook/Pilot/Navigation.xml
Resources/ServerInfo/Rules.txt

Because I'm way too lazy to swap branches
Disable emergency shuttle related systems
Cryopod is invincible
Blood is no longer "water" but now blood
Secret is out, xplor is in
Moon is added to navigation
It takes only 30 seconds rather than 1 minute for post round
Changed rules
You cant rename the ship twice

Tweaking misc changes

---

Resources/Prototypes/Roles/Jobs/Security/security_officer.yml

Merc greenwash

---

Resources/Prototypes/Roles/Jobs/Security/security_officer.yml

Revert merc greenwash

---

.gitignore
.gitmodules
Content.ServerSecret/Content.ServerSecret.csproj
Content.ServerSecret/GlobalUsings.cs
Content.ServerSecret/Program.cs
SpaceStation14.sln
Tools/package_client_build.py
Tools/setup_secrets.ps1

Lore goblins, your time is now

Add secrets

---

Resources/Maps/_FTL/kestrel.yml

Kestrel improvements

---

Content.Server/_FTL/ShipTracker/ShieldGeneratorComponent.cs
Content.Server/_FTL/ShipTracker/Systems/ShipTrackerSystem.Shields.cs
Content.Server/_FTL/ShipTracker/Systems/ShipTrackerSystem.cs
Resources/Prototypes/_FTL/Entities/Structures/Machines/shield_generator.yml

Shield generators no longer require power
Removed active shield generator component because of issues and also it was useless anyway

Shield generator patches

---

Content.Server/_FTL/SleeperCryopod/SleeperCryopodComponent.cs
Content.Server/_FTL/SleeperCryopod/SleeperCryopodSystem.cs
Resources/Prototypes/_FTL/Entities/Stations/independent.yml
Resources/Prototypes/_FTL/Entities/Structures/Machines/cryopod.yml
Resources/Prototypes/_FTL/Maps/trade-station.yml

* Ghosting in cryopods now adds a job slot
* You can now ghost/disconnect in cryopods and they will still put you into storage
* You can put SSD people in cryopods to store them into cryosleep storage
* Fixed cryopod sounds not working

Cryopod chicanery

---

Content.Server/_FTL/SleeperCryopod/SleeperCryopodComponent.cs
Content.Server/_FTL/SleeperCryopod/SleeperCryopodSystem.cs

fix /ghost and ssding not working in cryopods

---

Content.Client/Humanoid/HumanoidAppearanceSystem.cs
Content.Shared/Humanoid/Prototypes/SpeciesPrototype.cs
Resources/Prototypes/Entities/Mobs/Species/dwarf.yml
Resources/Prototypes/Species/dwarf.yml

fix height for dwarves

---

Resources/Maps/_FTL/hostile-escape-pod.yml
Resources/Prototypes/_FTL/ftl_points.yml

adds a hostile variant of the escape pod

hostile escape pod

---

Resources/Maps/_FTL/paper-plane.yml

Fix paper plane

---

Resources/Prototypes/_FTL/Entities/Markers/Spawners/enemy.yml
Resources/Prototypes/_FTL/Entities/Mobs/NPCs/enemy.yml

Adds some NPCs for mapping purposes

Hostile NPC Spawns

---

Content.Server/_FTL/FTLPoints/Effects/SpawnDungeonEffect.cs
Content.Server/_FTL/ShipTracker/Systems/ShipTrackerSystem.cs

Reverts ekrixi-14/ekrixi#148
This fucked up roundstart

Revert "Ruin fauna"

---

Resources/Prototypes/_FTL/ftl_points.yml

turn off worldgen again

---

Content.Server/_FTL/ShipTracker/Rules/EndOnShipDestruction/EndOnShipDestructionSystem.cs
Content.Server/_FTL/ShipTracker/Systems/ShipTrackerSystem.cs

Fixes the Nesasio not loading and ships being considered as "destroyed" even with the shuttle console enabled
Nesasio not loading explanation:
Ships being destroyed explanation:
Unoptimized code and outdated queries or something IDK an optimization literally just fixed it all

Fix ships randomly being destroyed

---

Resources/Prototypes/_FTL/Entities/Mobs/NPCs/trader_station.yml

make qms autospawn with microbombs

---

Resources/Maps/_FTL/fsc/nesasio.yml

Added a defib to med.
Fixed the nanomed position (maybe).
Added a crew monitoring server
Made the bar less pathetically vulnerable to spacing
Hand label
Just look at the image tbh

Nesasio fixes

---

Content.Server/Chat/Managers/ChatSanitizationManager.cs

Allow "idk." thru chatsan

---

Resources/ConfigPresets/Ekrixi/ekrixi.toml
Resources/ConfigPresets/Ekrixi/kryo.toml

Adds configurations for ekrixi

Server configurations

---

Resources/Maps/_FTL/acks/stormwalker.yml
Resources/Prototypes/_FTL/Maps/stormwalker.yml

I updated the stormwalker map I really hope this finally works PLEASE WORK
includes:
MV cables
cargo technician x999
a distinct lack of deckhands
the absence of janitors
one singular out of place window that I don't have the strength to change again
**THE MAP BEING SAVED INSTEAD OF THE GRID???**
**_BECOMESSTATIONCOMPONENT!!!!!!!!_**
I PUT ALL THIS IN THE FIRST TIME WHY WAS IT REVERTED???

storkwalmer

---

Resources/Maps/_FTL/acks/cestoda.yml
Resources/Prototypes/_FTL/Maps/cestoda.yml

title. also replaced the doors
god i hope this doesnt merge conflict

no more head roles on the cestoda

---

Resources/Maps/_FTL/acks/cestoda.yml

Cestoda surgical bag

---

Content.IntegrationTests/Tests/PostMapInitTest.cs
Resources/Prototypes/_FTL/Maps/kestrel.yml
Resources/Prototypes/_FTL/Maps/nesasio.yml
Resources/Prototypes/_FTL/Maps/paper-plane.yml
Resources/Prototypes/_FTL/Maps/stormwalker.yml
Resources/Prototypes/_FTL/Maps/trade-station.yml

fixes a lot of map-related test fails

Fix map-related test fails

---

Content.ServerSecret/Content.ServerSecret.csproj
Tools/setup_secrets.sh

Fixes Content.ServerSecret and fixes the linking on setup_secrets.sh

Fix secrets

---

Resources/Maps/_FTL/ships/cestoda.yml
Resources/Prototypes/_FTL/Maps/cestoda.yml

Downgraded the guns
2 AKMS -> 4 kardashev mosins
added a couple bowls
removes 1 catwalk
removed the hidden wt550
replaced the pilot's coffee with energy drinks, they need it
filled the ale bottle in the booze closet because i didnt realized it was empty
re-canonized the lore note by changing one word
rain asked for worse guns, then i started fixing stuff myself

Cestoda updates

---

Resources/Prototypes/_FTL/Entities/Mobs/Customization/IPC_facial_hair.yml
Resources/Prototypes/_FTL/Entities/Mobs/Customization/IPC_hair.yml
Resources/Prototypes/_FTL/Entities/Mobs/Customization/Markings/IPC_marking.yml
Resources/Prototypes/_FTL/Species/ipc.yml

Moves IPC markings to hair and marking [#257](https://github.com/ekrixi-14/ekrixi/issues/257)
**Changelog**
no cl

IPC hair/facial hair

---

Resources/Prototypes/Roles/Jobs/Command/captain.yml
Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml
Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
Resources/Prototypes/_FTL/Roles/Jobs/Command/pilot.yml

Adds pagers to roles roundstart (excluding deckhands)
#269 
Belt: 
Medical Doctor (removes medical belt)
Pilot
Pockets:
Captain (removes antique laser)
Mercenary
Engineer (moves meson to eyes)
**Changelog**
no cl

Pager Invertory 

---

Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml
Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/satchel.yml

Closes #272
Adds eye protection to engineering

Engineering eye protection

---

Resources/Maps/_FTL/ai/spark-class.yml

"Did I forget to link the guns?"
I did in fact forget to link the guns
This is now fixed.

Fix the gun linking on the spark class

---

Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
Resources/Prototypes/Catalog/Fills/Lockers/medical.yml
Resources/Prototypes/Roles/Jobs/Civilian/assistant.yml
Resources/Prototypes/Roles/Jobs/Command/captain.yml
Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml
Resources/Prototypes/Roles/Jobs/Security/security_officer.yml

They don't exist at all!!!
goodbye radios...
removes earpiece and overhead radios from starting loadouts and lockers that have extras
we have cool handhelds now!

No more radios

---

Resources/Maps/_FTL/ships/myrmeleon.yml

Dolicho and Blatto now have BecomesStation, which means they should actually spawn on roundstart
added a bottle of universal enzyme to the kitchen freezer because there's soy seeds roundstart that it can be used with
added one additional sign for my own conscience
also added 3 RV8 injectors to pilot's freezer
without the shuttles the map just didn't work. now it should I HOPE

Myrmeleon patch

---

Content.Server/_FTL/Pager/PagerReceiverComponent.cs

I changed 5 lines.
Rain told me to

Make PagerRecieverComponent able to be vv-ed

---

Resources/Prototypes/_FTL/Entities/Structures/Machines/warp-drive.yml

warp drive aio port is now the spin drive aio port
LOOOOOOOOOOORE

Warp drive is now the spin drive

---

Content.Server/_FTL/FTLPoints/Systems/FtlPointsSystem.cs

That^
Fixes the softlock due to stars being too far
People hate being softlocked
Lowered the max range at which next "branch" star spawns, as well as lowering other values slightly, just to make sure nothing weird happens when like 3 stars roll the highest number
**Changelog**

Fixed softlock due to stars being too far(#306)
